import AVFoundation
import AVKit
import Foundation
import PamNative
import UIKit

public final class VideoPlayerFactory: NativeViewFactory, @unchecked Sendable {
    public init() {}
    public func create(context:AnyObject?,emit:@escaping(Data)->Void)->UIView{VideoContainerView(emit:emit)}
    public func update(view:UIView,properties:[String:WireValue]){(view as? VideoContainerView)?.update(properties)}
    public func release(view:UIView){(view as? VideoContainerView)?.releasePlayer()}
}

private final class VideoContainerView:UIView,@unchecked Sendable {
    private let controller=AVPlayerViewController();private let player=AVPlayer();private let emit:(Data)->Void
    private var source="";private var requestedSeek:Int64 = -1;private var loops=false;private var periodic:Any?;private var endToken:NSObjectProtocol?;private var statusObservation:NSKeyValueObservation?;private var fairPlay:FairPlayResourceLoader?
    init(emit:@escaping(Data)->Void){self.emit=emit;super.init(frame:.zero);controller.player=player;controller.view.frame=bounds;controller.view.autoresizingMask=[.flexibleWidth,.flexibleHeight];addSubview(controller.view);endToken=NotificationCenter.default.addObserver(forName:.AVPlayerItemDidPlayToEndTime,object:nil,queue:.main){[weak self] note in guard let self,let item=note.object as? AVPlayerItem,item===self.player.currentItem else{return};self.send(["event":.integer(1),"state":.integer(4)]);if self.loops{self.player.seek(to:.zero);self.player.play()}}}
    required init?(coder:NSCoder){nil}
    func update(_ values:[String:WireValue]){let nextSource=values.text("source");if nextSource != source{source=nextSource;load(nextSource,values)};controller.showsPlaybackControls=values.flag("controls",true);controller.videoGravity=whenResize(values.integer("resizeMode",1));player.isMuted=values.flag("muted",false);player.volume=Float(values.decimal("volume",1)).clamped;let seek=values.integer("positionMillis",0);if seek != requestedSeek{requestedSeek=seek;if seek>0{player.seek(to:CMTime(value:seek,timescale:1000),toleranceBefore:.zero,toleranceAfter:.zero)}};let rate=Float(max(0.25,min(4,values.decimal("playbackRate",1))));if values.flag("autoPlay",false){player.playImmediately(atRate:rate)}else{player.pause()};player.currentItem?.preferredPeakBitRate=Double(max(0,values.integer("preferredPeakBitRate",0)));player.currentItem?.preferredForwardBufferDuration=Double(max(0,values.integer("preferredForwardBufferMillis",0)))/1000;configureTicker(values.integer("progressIntervalMillis",500));loops=values.flag("loop",false);player.actionAtItemEnd=loops ? .none:.pause}
    private func load(_ source:String,_ values:[String:WireValue]){let url:URL;if source.hasPrefix("https://"){guard let remote=URL(string:source)else{failure("Invalid video URL");return};url=remote}else{do{url=try sandboxURL(source)}catch{failure(String(describing:error));return}};let item:AVPlayerItem;if values.integer("drmScheme",0)==2{guard let certificate=URL(string:values.text("drmCertificateUrl")),let license=URL(string:values.text("drmLicenseUrl")),certificate.scheme=="https",license.scheme=="https",!values.text("drmContentId").isEmpty else{failure("Invalid FairPlay configuration");return};let asset=AVURLAsset(url:url);let loader=FairPlayResourceLoader(certificateURL:certificate,licenseURL:license,contentID:values.text("drmContentId"),authorization:values.text("drmAuthorization"));asset.resourceLoader.setDelegate(loader,queue:DispatchQueue(label:"dev.pam.video.fairplay"));fairPlay=loader;item=AVPlayerItem(asset:asset)}else{fairPlay=nil;item=AVPlayerItem(url:url)};statusObservation=item.observe(\.status,options:[.new]){[weak self] item,_ in DispatchQueue.main.async{guard let self else{return};switch item.status{case .readyToPlay:self.send(["event":.integer(1),"state":.integer(3)]);case .failed:self.failure(item.error?.localizedDescription ?? "Playback failed");default:self.send(["event":.integer(1),"state":.integer(2)])}}};player.replaceCurrentItem(with:item)}
    private func configureTicker(_ milliseconds:Int64){if let periodic{player.removeTimeObserver(periodic);self.periodic=nil};let interval=max(100,min(10_000,milliseconds));periodic=player.addPeriodicTimeObserver(forInterval:CMTime(value:interval,timescale:1000),queue:.main){[weak self]_ in guard let self else{return};let duration=self.player.currentItem?.duration.seconds ?? 0;let buffered=self.player.currentItem?.loadedTimeRanges.last?.timeRangeValue.end.seconds ?? 0;self.send(["event":.integer(2),"positionMillis":.integer(Int64(max(0,self.player.currentTime().seconds)*1000)),"durationMillis":.integer(duration.isFinite ? Int64(max(0,duration)*1000):0),"bufferedMillis":.integer(buffered.isFinite ? Int64(max(0,buffered)*1000):0)])}}
    private func whenResize(_ value:Int64)->AVLayerVideoGravity{switch value{case 2:return .resizeAspectFill;case 3:return .resize;default:return .resizeAspect}}
    private func sandboxURL(_ path:String)throws->URL{let root=FileManager.default.urls(for:.applicationSupportDirectory,in:.userDomainMask)[0].standardizedFileURL;let target=root.appendingPathComponent(path).standardizedFileURL;guard target.path.hasPrefix(root.path+"/")else{throw VideoError.invalidPath};return target}
    private func failure(_ message:String){send(["event":.integer(3),"state":.integer(5),"message":.text(message)])}
    private func send(_ values:[String:WireValue]){if let data=try? WireMap.encode(values){emit(data)}}
    func releasePlayer(){if let periodic{player.removeTimeObserver(periodic);self.periodic=nil};if let endToken{NotificationCenter.default.removeObserver(endToken);self.endToken=nil};statusObservation=nil;fairPlay=nil;player.pause();player.replaceCurrentItem(with:nil)}
    deinit{releasePlayer()}
}
private extension Dictionary where Key==String,Value==WireValue{func text(_ key:String)->String{if case let .text(v)?=self[key]{return v};return ""};func flag(_ key:String,_ fallback:Bool)->Bool{if case let .flag(v)?=self[key]{return v};return fallback};func integer(_ key:String,_ fallback:Int64)->Int64{if case let .integer(v)?=self[key]{return v};return fallback};func decimal(_ key:String,_ fallback:Double)->Double{switch self[key]{case let .decimal(v)?:return v;case let .integer(v)?:return Double(v);default:return fallback}}}
private extension Float{var clamped:Float{min(1,max(0,self))}}
private enum VideoError:Error{case invalidPath}
